name: Build

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Build Web Interface
      run: npm run build
      env:
        CI: true
    - name: Install Pods
      run: cd ./ios && pod install
    - name: Build
      run: cd ./ios && xcodebuild build -workspace Plugin.xcworkspace -scheme Plugin -sdk iphoneos
    - name: Build docs
      run: npm run docs
    - name: Commit generated docs
      run: |
        git config --local user.email "me@danielsogl.de"
        git config --local user.name "Daniel Sogl"
        git commit -m "docs(pages): update documentation" -a
    - run: git pull
    - run: git status
    - name: Push docs to master
      uses: ad-m/github-push-action@master
      with:
        directory: ./docs
        github_token: ${{ secrets.GITHUB_TOKEN }}

