name: iOS

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Pods
      run: |
        cd ./ios
        pod install
    - name: Build
      run: |
        cd ./ios
        xcodebuild build -workspace Plugin.xcworkspace -scheme Plugin
